global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: orchid-demo-app
    static_configs:
      - targets: ["demo-app:9464"]

  - job_name: otel-collector-otlp-metrics
    static_configs:
      - targets: ["otel-collector:8889"]
